service: workout-assistant-api

useDotenv: true

provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64
  region: ap-south-1
  timeout: 15
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    JWT_SECRET: ${env:JWT_SECRET}
    APP_NAME: ${env:APP_NAME}
    APP_VERSION: ${env:APP_VERSION}

functions:
  api:
    handler: bootstrap
    events:
      - httpApi: "*"

package:
  individually: true
  patterns:
    - "!**"
    - "bootstrap"
